base/etc/one-context.d/02-ssh_public_key
Make sure to retrieve ${HOME} location from getent.
=> Contextualize SSH user with $USERNAME variable

base/etc/one-context.d/10-set-username-password
User provides either a clear text ${PASSWORD} or a crypted
${CRYPTED_PASSWORD}.
=> Set ${CRYPTED_PASSWORD} for ${USERNAME}

base.one/etc/one-context.d/05-grow-rootfs
tested (lvm and normal partitions) with centos 7 and debian 8 (although there seems to be a bug in growpart)
=> Changed to try and handle both lvm and regular partitions

src/etc/one-context.d/loc-10-network##deb.one, src/etc/one-context.d/loc-10-network##rpm.one, src/etc/one-context.d/loc-10-network-pci##one
Support for
* full (static) IPv6 addresses
* ULAs
Note: network configuration for PCI passthrough device must be tested.
Closes #54
=> Improved IPv6 support

postinstall.one, src/etc/one-context.d/loc-10-network##rpm.one, src/etc/one-context.d/loc-11-dns##one, src/etc/one-context.d/loc-23-selinux-ssh##rpm, src/etc/one-context.d/net-15-hostname##one
Tested on openSUSE Leap 42.2 is working fine!
=> Add: openSUSE support

src/etc/one-context.d/loc-10-network##rpm.one
Signed-off-by: Kristián Feldsam <feldsam@gmail.com>
=> Fixed IPv6 network on OpenSuse 42.2

src/etc/one-context.d/loc-10-network##arch.one
Fixed generate network config for systemd-networkd.
=> Fixed generate network config for systemd-networkd.

src/etc/one-context.d/loc-10-network##apk.one, src/etc/one-context.d/loc-10-network##deb.one, src/etc/one-context.d/loc-10-network##rpm.one
* Add alias debian context.
* Add alias centos context.
* Add alias alpine context.
=> F #911: Add alias/es support

src/etc/one-context.d/loc-09-timezone
=> F #165: Setup TIMEZONE

src/etc/one-context.d/loc-10-network##apk.one, src/etc/one-context.d/loc-10-network##arch.one, src/etc/one-context.d/loc-10-network##bsd.one, src/etc/one-context.d/loc-10-network##deb.one, src/etc/one-context.d/loc-10-network##rpm.one
fix get_network to calc the net address correctly
=>  F #NA: fix get_network to calc the net address correctly

src/usr/bin/onegate.rb
=> B OpenNebula/one#3572: add updated onegate client

src/usr/sbin/one-contextd
- Add a third option to looking for the context device.
- Remove mounting type.
=> F OpenNebula/one#4089: Add changes for Firecracker context support

src/usr/bin/onegate.rb
- Sync onegate with OpenNebula repo one.c
=> B OpenNebula/one#3571: sync context onegate with one

pkg/postinstall, src/etc/one-context.d/loc-10-network##network-scripts.one, src/etc/one-context.d/loc-10-network-pci##one
- fix CentOS network scripts to utilize network routes as other systems
- minor refactor
=> B #83: Fix route metrics for CentOS

src/usr/bin/onegate.rb
=> M #-: add OneGate Header

src/etc/one-context.d/loc-16-gen-env
+ fix error when CONTEXT_FILE is empty (not likely)
+ fix other warning/error messages shown in the log
+ make the script compliant with shellshock
=> B #212: Fix chown command on FreeBSD

src/etc/one-context.d/loc-04-run-dir, src/etc/one-context.d/loc-04-tmpfs
=> M #-: add script to recreate /run dir

src/usr/bin/onegate.rb
=> B #5258: remove comma after shutdown

src/etc/one-context.d/net-98-execute-scripts
=> M #-: Fix init scripts

src/etc/one-context.d/net-99-report-ready
=> F OpenNebula/addon-context-windows#85: Retry READY

README.md, generate.sh
=> M #-: Update README

src/etc/one-context.d/loc-05-grow-rootfs
=> B #266: Fix GROW_ROOTFS and GROW_FS on btrfs

src/etc/one-context.d/loc-05-grow-rootfs
=> B #266: Workaround old broken util-linux
