base_deb/etc/one-context.d/00-network
base_rpm/etc/one-context.d/00-network

Some hosts configurations can to require to add different MTU values in their guests, for example if you are using openvswitch with gre support, the guests requires MTU=1420.

Add MTU support to network devices

---

base_deb/etc/one-context.d/00-network

In Ubuntu 12.04 ifquery don't have any option "-l" we need to pass --list instead.
Debian 8 ifquery don't have this "-l" option.

Fix ifquery error on Debian based OS like ubuntu

---

base/etc/one-context.d/07-grow-rootfs

If the virtual machine don't have cloud-utils intalled this script print errors.
I test if growpart command is available before running the action

Fix growpart error when missing.

---

base/etc/one-context.d/04-mount-swap

Instead of using the swap label the swap script will find and swapon all available swap spaces.  This allows for images which may not have the swap setup in the fstab to utilize that swap.

Swap script will now swap on all available swap spaces

---

base/etc/one-context.d/02-ssh_public_key

The ```touch``` will fail if the directory does not exist.

Create SSH directory before authorized_keys file

---

base_arch/etc/one-context.d/05-hostname
base_deb.one/etc/one-context.d/05-hostname
base_rpm.one/etc/one-context.d/05-hostname

When setting the hostname from `$SET_HOSTNAME`, replace any characters
not allowed in hostnames (as specified in RFC 952) with a hyphen.
This is enables a VM template to safely use the VM's name as the
hostname (by setting the context variable `SET_HOSTNAME=$NAME`).

Replace unsafe characters in SET_HOSTNAME.

---

base_deb.one/etc/one-context.d/00-network

add the records only to the first (`eth0`) interface, since it is
not possible to have multiple `dns-nameservers` and `dns-search`
entries in the `/etc/network/interfaces` file.
closes #30

Used 02-dns calls to gather search/dns records

---

base_rpm.one/etc/one-context.d/15-hostname

On RHEL and CentOS 7 host name is kept in /etc/hostname, so even if SET_HOSTNAME has a value, the machine was keeping  localhost.localdomain as name. This way the hostname file gets overwritten with contextualization variable value. I'm supposing that file /etc/hostname will be existing in next releases too (OS_VERSION >= 7)

Modifying file /etc/hostname to set the hostname

---

base.one/etc/one-context.d/05-grow-rootfs

Add an entry in the growroot script that checks for btrfs and executes a
`btrfs filesystem resize max /`
if `/` is a btrfs filesystem.

Add btrfs to list of FS that growroot will resize.

---

base_deb.one/etc/one-context.d/10-network
base_rpm.one/etc/one-context.d/10-network

This feature is already present in EL scripts:
b513d94c96ceb0b2efd2a1655fdad4a4f343232c
c2316a74debd9ef0f1633ddbf20584b8c06ad3d3

On Debian always use IPv4 if available, disable IPv6 autoconfiguration

---

README.md

Fails with "ERROR: Unrecognised option '--output-type'"

README.md update: fpm 1.6.2 doesn't work anymore

---

postinstall.one

/run/systemd/system/ doesn't exist if you're installing the context RPM with virt-customize.

Fix systemd check on service registration

---

src/etc/one-context.d/loc-05-grow-rootfs##one

In Ubuntu 16.04 server default LVM installation with one disc, there is msdos partition table and the PV is in the extended partition. When growing the PV, you must resize the extended partition first and the PV partition second. This change detects the situation and grows both items in msdos (MBR) partition table accordingly.

Please update 05-grow-rootfs##one to work with msdos partitioning and LVM in extended partition

---

src/etc/one-context.d/loc-20-set-username-password

If use a $GRANT_SUDO variable with $USERNAME,
the regular user will have a sudo privileges
#88

Add GRANT_SUDO parameter to context

---

src/etc/one-context.d/loc-10-network##arch.one

- add DNS and Domain support in systemd network unit
- IPV6 -> IP6

add DNS and Domain support in systemd network unit

---

src/etc/one-context.d/loc-15-keepalived##apk

I built this mostly for our own use but I figured I would send you a pull request in case you all want to use it.  If not feel free to close this.
These additions make it possible to pass an alpine image a keepalived check script.  We are using this to check that HAProxy is running on an alpine vrouter so that we can build a virtual load balancer.
Also if you all do want to use this let me know if there is anything you would like me to change before merging.

Add functionality for keepalived check script

---

src/etc/one-context.d/loc-10-network##apk.one
src/etc/one-context.d/loc-10-network##arch.one
src/etc/one-context.d/loc-10-network##deb.one
src/etc/one-context.d/loc-10-network##rpm.one
src/usr/sbin/one-contextd

Some modifications were required to the context package
- interface name parsing due to the network name-spacing introducing `@` in the ip command output
- handling not existing ISO mounts in container. Context ISO is mounted on the host and passed trough to the container
The contextualization shouldn't interfere with KVM

LXD drivers contextualization

---

src/etc/one-context.d/net-99-report-ready

Put onegate to the last resort to prevent potential failures with missing ruby or hanging due to low entropy.

B #125 Reorder sending ready report

---

src/lib/udev/rules.d/65-context.rules##rpm.systemd.one

device that has `ID_CDROM=1` set in the udev environment.
This will prevent re-contextualization of the host in case when an VM is LXD or KVM host (nested virtualization)

B #138 run contextualization only from CDROM

---

targets.sh

As pointed [here](https://github.com/OpenNebula/addon-context-linux/issues/145#issuecomment-469620915) xenial requires dbus in order for hostname contextualization to work

Fix hostname contextualization on Ubuntu xenial

---

src/etc/one-context.d/loc-05-grow-rootfs

findmnt tested on Alpine, CentOS, Ubuntu, Fedora.

B #148: Use findmnt to find / device

---

README.md

I have tested it with automatic images generation:
https://github.com/kvaps/opennebula-images/blob/master/mkimage.fedora
Fedora 30 is working fine

F #-: Add fedora 30 to tested platforms

---

src/usr/lib/systemd/system/one-context-force.service##systemd.one

We must make sure "one-context-force.service" is not run during boot disk
detection but on hotplug events.
When booting with a swap partition on the disk, the udev rules will
start the "one-context-force" service long before "one-context-local"
and "one-context".
This results in the system being in "degraded" state as reported by
"systemctl is-system-running".
* src/usr/lib/systemd/system/one-context-force.service##systemd.one:
add conditions to run only on hotplug events.

B #118: one-context-force breaks boot status

---

src/etc/one-context.d/loc-10-network##apk.one
src/etc/one-context.d/loc-10-network##bsd.one
src/etc/one-context.d/loc-10-network##deb.one
src/etc/one-context.d/loc-10-network##rpm.one

B #174: add support for ALIAS_DETACH

---

src/etc/one-context.d/loc-10-network##deb.one
targets.sh

ifupdown2 is an alternative to classic ifupdown
https://github.com/CumulusNetworks/ifupdown2
It's allow to reload online network configuration with dependencies
and 100% compatible with classic ifupdown1 config.
Signed-off-by: Alexandre Derumier <aderumier@odiso.com>

debian: add ifupdown2 support

---

generate.sh
src/etc/one-context.d/net-97-start-script
src/etc/one-context.d/net-98-execute-scripts
src/usr/sbin/one-contextd
src/usr/sbin/onesysprep

Introduce new OpenNebula directory /var/lib/one-context where a new tmp
directory is located. This new one will not be mounted with noexec
option on any system by default.
Add cleanup handler on the script exit and ensure the correct return
code for the init scripts (if one or more fail then return non-zero).
Update onesysprep and set its version by generate.sh script.

B #112: Move script location outside of /tmp

---

src/etc/one-context.d/loc-05-grow-rootfs

Add new context variable 'GROW_FS' which can contain list of directories
(mount-points) separated by spaces.
If GROW_ROOTFS is set to 'YES' then the rootfs will be added in the case
when GROW_FS does not contain '/'.
FreeBSD is not supported yet and will skip non-rootfs resize.
NOTE: The disk name must follow the simple scheme <name>[<part>] where
name cannot contain any numeric and the part must be only a numeric,
e.g.: /dev/sda1
(Arbitrary disk names are not supported, e.g.: /dev/mapper/luks-1234)

Add non-rootfs resize

---

src/usr/sbin/one-contextd

- In case the CD-ROM is not mounted "glabel status | grep CONTEXT | awk '{print $3}'"
will have a null string which will eventually assign the value "/dev/" to "dev_context"
variable. In later occasions while existence of "dev_context" is checked it will
always return true and no elif conditions will be executed. Add additional glabel check
for BSD.
- In case the CD-ROM is not mounted and used there is nothing to unmount and eventually
trying to unmount will throw error. So add an additional check to see if "MOUNT_DIR" is
used as any mount points or not.
- briefly describe change here,
- briefly describe change here,
- briefly describe change here.

Fix some errors in FreeBSD 13

---

src/usr/sbin/onesysprep
targets.sh

The default 'awk' _alternative_ on the Debian is an old mawk of version
1.3.3 with plenty of bugs and problems. One of them is the lack of
support for POSIX regex character classes which old mawk does not know
despite the fact that it does advertise a support for extended regex (as
egrep for example).
This was reported and fixed in 2009 with version of 1.3.4 but Debian is
still using the old unfixed version 1.3.3:
https://bugs.launchpad.net/ubuntu/+source/mawk/+bug/69724
This commit workaround this issue by simple test and possible abort if
the usage of an incompatible awk implementation is unreasonable - user
choice.
Note: Currently just only two optional (non-default) tests are skipped
due to this issue.

B #231: Workaround the mawk issue on Debian

---

src/usr/sbin/onesysprep

M #-: Add additional log files to be deleted.
Ubuntu systems have log files in /var/log/landscape and
/var/log/unattended-upgrades. The files in these directories
are not removed by the onesysprep tool. This patch add the
aforementioned directories.
Signed-off-by: Remy Zandwijk <remy@luckyhands.nl>

Add additional (Ubuntu) log files to be deleted.

---

generate.sh
targets.sh

New variable RECOMMENDS can be used as a weak dependency list on rpm and
deb based distros.
The package open-vm-tools is moved to RECOMMENDS on el7 and el8 due to
the absence of arm64 version of these packages in RH distros.

F one-infra#39: Add weak dependency support

---

src/usr/sbin/one-contextd

- Change the value of `LANG` to `C` (POSIX) which is more generic
- `LANG` can be insufficient and will not override `LC_TIME` for example if that was set
- `LC_ALL` will ensure that all categories of locale are POSIX C
- This commit also provides a way for the scripts to find the original locale via `_one_orig_*` variables if that would be needed

B #251: Enforce POSIX C locale

---

src/usr/sbin/one-contextd

Scripts run by one-contexd will not be executed in a subshell - this
will fix the issue with the START_SCRIPT which would hold the boot if
any long-running process would originate in it (e.g. daemon/service).
User still will need to do something like this inside the START_SCRIPT
(or any other context script) otherwise SIGTERM will be sent:
nohup service nginx start &

F #265: Improve START_SCRIPT

---

README.md
generate-all.sh
targets.sh

Since EL9 does not contain the legacy network scripts, add EL9 support
without network-scripts dependency
Tested on AlmaLinux OS 9 Beta 1 [x86_64](https://repo.almalinux.org/almalinux/9/cloud/x86_64/images/) and [AArch64](https://repo.almalinux.org/almalinux/9/cloud/aarch64/images/) OpenNebula Images
Resolves #267 
Signed-off-by: Elkhan Mammadli <elkhan.mammadli@protonmail.com>

F #267: Add EL9 support

---

src/etc/one-context.d/loc-15-keepalived##vr

This functionality is intended to allow to indicate the path to a notification script for Keepalived.
We added this feature mostly for our own use but believe it may be useful for others.

Add functionality for keepalived notify script

---

src/etc/one-context.d/loc-10-network.d/functions
src/etc/one-context.d/loc-10-network.d/netcfg-bsd
src/etc/one-context.d/loc-10-network.d/netcfg-interfaces
src/etc/one-context.d/loc-10-network.d/netcfg-netplan
src/etc/one-context.d/loc-10-network.d/netcfg-networkd
src/etc/one-context.d/loc-10-network.d/netcfg-nm
src/etc/one-context.d/loc-10-network.d/netcfg-scripts

- The flag was being set only for interfaces. Now it is called on the function every network renderer uses
- [This](https://github.com/OpenNebula/docs/commit/d01ad842e6f588cd84e49fd23528aa102c72ebea)

F OpenNebula/addon-context-linux#277 Fix onegate proxy static route

---

src/etc/one-context.d/loc-10-network.d/functions
src/etc/one-context.d/loc-10-network.d/netcfg-bsd
src/etc/one-context.d/loc-10-network.d/netcfg-interfaces
src/etc/one-context.d/loc-10-network.d/netcfg-netplan
src/etc/one-context.d/loc-10-network.d/netcfg-networkd
src/etc/one-context.d/loc-10-network.d/netcfg-nm
src/etc/one-context.d/loc-10-network.d/netcfg-scripts

Minor code improvements. Similar to setting the flag
```
export onegate_proxy_route_missing="yes" # flag route not setup
```
the onegate_ip is now read in only one place

F OpenNebula/addon-context-linux#277 cleaner code

---

src/etc/one-context.d/loc-10-network.d/netcfg-scripts

SUSE scripts network renderer implementation wasn't considered for static routing

F OpenNebula/addon-context-linux#277 Fix SUSE static routing

---

src/etc/one-context.d/net-15-hostname

populating `/etc/hosts` fails on DockerHub images because the file exists, but it is empty. So this condition triggers
```
elif [ -f /etc/hosts ]; then
eval "${SED_I} -e \"1s/^/${entry}\"$'\\\\\n/' /etc/hosts"
```
and nothing happens. Now it is `-s` which will check both that the file exists and is not empty. When empty, next condition (else) will be checked and the entry will be forcibly written.
Some linting as well
Closes OpenNebula/one#6174
No doc PR required since it is a context problem. When the release is made it will be added to the context changelog

B OpenNebula/one#6174: Consider /etc/hosts being empty
